# Generated by Django 5.1.6 on 2025-02-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auction_userprofile_role_bid_car_auction_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('бензин', 'бензин'), ('газ', 'газ'), ('дизел', 'дизел')], max_length=20, verbose_name='Тип топлива'),
        ),
    ]
